version: 0.2

run-as: root


phases:
   pre_build:
     commands:
       - apt update
       - apt upgrade -y
       - apt autoremove --purge
       - apt install nginx -y
       - apt install php php-fpm -y

   build:
     commands:
        - echo "build application"
       

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
