version: 0.2

run-as: root

env:
  parameter-store:
            DB_NAME: "/prajwal/DB_NAME"
            DB_USER: "/prajwal/DB_USER"
            DB_PASSWORD: "/prajwal/DB_PASSWORD"

phases:
   pre_build:
     commands:
       - apt update
       - apt upgrade -y
       - apt autoremove --purge
       - apt install nginx -y
       - apt install php php-fpm -y

   build:
     commands:
        - echo "build application 'date' "
       

artifacts:
  files:
    - echo "Upload artifact to bucket for codedeploy"
    - '**/*'
